// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `job_queue` table.
    ///
    /// (Automatically generated by Diesel.)
    job_queue (name) {
        /// The `name` column of the `job_queue` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `scheduled_execution_time` column of the `job_queue` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        scheduled_execution_time -> Timestamptz,
        /// The `in_progress` column of the `job_queue` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        in_progress -> Bool,
    }
}

diesel::table! {
    /// Representation of the `languages` table.
    ///
    /// (Automatically generated by Diesel.)
    languages (id) {
        /// The `id` column of the `languages` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `english_name` column of the `languages` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        english_name -> Text,
    }
}

diesel::table! {
    /// Representation of the `sessions` table.
    ///
    /// (Automatically generated by Diesel.)
    sessions (id) {
        /// The `id` column of the `sessions` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Bytea,
        /// The `expiry` column of the `sessions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        expiry -> Timestamptz,
        /// The `username` column of the `sessions` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 50]
        username -> Nullable<Varchar>,
    }
}

diesel::table! {
    /// Representation of the `test_can_be_safely_dropped_in_production` table.
    ///
    /// (Automatically generated by Diesel.)
    test_can_be_safely_dropped_in_production (id) {
        /// The `id` column of the `test_can_be_safely_dropped_in_production` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `name` column of the `test_can_be_safely_dropped_in_production` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (name) {
        /// The `name` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `password_hash` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        password_hash -> Nullable<Text>,
        /// The `login_attempt_count` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        login_attempt_count -> Int4,
        /// The `failed_login_attempt_count` column of the `users` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        failed_login_attempt_count -> Int4,
        /// The `next_login_attempt_count_reset` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        next_login_attempt_count_reset -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `word_types` table.
    ///
    /// (Automatically generated by Diesel.)
    word_types (id) {
        /// The `id` column of the `word_types` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int4,
        /// The `english_name` column of the `word_types` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        english_name -> Text,
    }
}

diesel::table! {
    /// Representation of the `words` table.
    ///
    /// (Automatically generated by Diesel.)
    words (word, word_type, language) {
        /// The `word` column of the `words` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        word -> Text,
        /// The `word_type` column of the `words` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        word_type -> Int4,
        /// The `language` column of the `words` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        language -> Int4,
    }
}

diesel::joinable!(sessions -> users (username));
diesel::joinable!(words -> languages (language));
diesel::joinable!(words -> word_types (word_type));

diesel::allow_tables_to_appear_in_same_query!(
    job_queue,
    languages,
    sessions,
    test_can_be_safely_dropped_in_production,
    users,
    word_types,
    words,
);
