#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER rvoc WITH PASSWORD '$POSTGRES_RVOC_PASSWORD';
	CREATE DATABASE rvoc;
	GRANT ALL PRIVILEGES ON DATABASE rvoc TO rvoc;
EOSQL
