name: Nix Lints

on:
  push:
    paths:
      # Run if workflow changes
      - '.github/workflows/nix-lints.yml'
      # Run on changed flake
      - 'flake.nix'
      - 'flake.lock'
    branches:
      - main
  pull_request:
    branches: main
  # Run manually
  workflow_dispatch:

jobs:
  nix_fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v22

    - name: Cache /nix/store
      uses: actions/cache@v3
      with:
        path: /nix/store
        key: ${{ runner.os }}-${{ hashFiles('flake.*') }}-${{ hashFiles('.github/workflows/web-api-ci.yml') }}

    - name: Check nix formatting
      run: nix fmt --accept-flake-config -- --check .
    
  nix_dead_code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v22

    - name: Cache /nix/store
      uses: actions/cache@v3
      with:
        path: /nix/store
        key: ${{ runner.os }}-${{ hashFiles('flake.*') }}-${{ hashFiles('.github/workflows/web-api-ci.yml') }}

    - name: Check for dead nix code
      run: nix run github:astro/deadnix -- --fail .